services:
  # Frontend service
  # app:
  #   build:
  #     context: ./front-end
  #     dockerfile: Dockerfile
  #   container_name: front-end
  #   ports:
  #     - 8080:80
  #   networks:
  #     - app_network

  # Backend API service
  # api:
  #   container_name: api
  #   build:
  #     context: ./api
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DB_HOST=${DB_HOST}
  #     - DB_NAME=${DB_NAME}
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - JWT_SECRET=${JWT_SECRET}
  #   depends_on:
  #     - db
  #   networks:
  #     - app_network

  # PostgreSQL database service
  db:
    container_name: db
    image: postgres:12.20-alpine
    environment:
      POSTGRES_DB: finso
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

# Networks for service communication
networks:
  app_network:
    driver: bridge
