services:
  app:
    container_name: front-end
    build:
      context: ./front-end
      dockerfile: Dockerfile
      target: dev
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
    ports:
      - "5173:5173"
    volumes:
      - ./front-end:/app

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
