services:
  # Frontend service
  # app:
  #   build:
  #     context: ./front-end
  #   ports:
  #     - "8080:80" # Expose port 80 from the container to 8080 on the host
  #   depends_on:
  #     - api # Ensure frontend starts after API
  #   networks:
  #     - app_network

  # Backend API service
  # api:
  #   build:
  #     context: ./api
  #   ports:
  #     - "3000:3000" # Expose port 3000 from the container to 3000 on the host
  #   environment:
  #     MONGO_URL: mongodb://mongo:27017/mydb
  #   depends_on:
  #     - mongo # Ensure API starts after MongoDB
  #   networks:
  #     - app_network

  # PostgreSQL database service
  db:
    image: postgres:12.20-alpine
    environment:
      POSTGRES_DB: finso
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:

# Networks for service communication
networks:
  app_network:
    driver: bridge
